export const GRAVITY = -25;
export const RESTITUTION_TABLE = 0.25; // how much fruits bounce off the table
export const RESTITUTION_FRUIT = 0.35; // how much fruits bounce off each other
export const RESTITUTION_WALL = 0.2; // how much fruits bounce off the cup wall
export const FRICTION_TABLE = 0.3; // slows fruits sliding on the table / cup floor
export const FRICTION_WALL = 0.4; // slows fruits scraping along the cup wall
export const LINEAR_DAMPING = 0.995; // air resistance, applied every frame
export const ANGULAR_DAMPING = 0.90; // how fast spin dies out
export const COLLISION_SPIN = 0.35; // how much a collision makes a fruit tumble
export const FRUIT_COLLIDE_EPS = 0.001; // tiny gap so fruits don't overlap exactly
export const SLEEP_SPEED = 0.03;
export const SLEEP_FRAMES = 20;
export const POSITION_EPS = 0.0005;
export const COLLISION_PASSES = 15;
export const TOP_OUT_LIMIT = 2.0; // seconds a fruit can stick out before game over
export const MAX_ANGULAR_SPEED = 6.0; // fastest a fruit is allowed to spin
